
<style>
    .theme_name{
        width: 100%;
        position: absolute;
        top:-40px;
    }
    .theme_name label{
        padding:5px;
        float:left;
        
    }
</style>
<script>
    $(function(){
        $(".windowGrid .item").live('mouseenter',function(){
            $(this).find('div.theme_name').animate({'top':0},'fast');
        }).live('mouseleave',function(){

            $(this).find('div.theme_name').stop(true,false).animate({'top':'-40px'});
        });
    });
</script>
 

<div class="windowGrid">

    <?php foreach ($this->app['themes'] as $theme) { ?>

        <div class="item span3">
            
            <div class="theme_name trans">
                <label><?php echo $theme['theme_name'];?></label>   
            </div>
                
            <a href="<?php echo $this->app['url'];?>window/theme/themeid/<?php echo $theme['theme_id'];?>" class="editTheme">
                <img src="themes/<?php echo $theme['theme_folder']; ?>/screenshot.jpg" width="100%" height="170">
            </a>
            <div class="controll trans">
                <a href="<?php echo $this->app['url'];?>window/theme/themeid/<?php echo $theme['theme_id'];?>" class='editTheme'>Edit</a>
                
                <a href="?theme=<?php echo $theme['theme_id'];?>" class="disAjax">Preview</a>
                
                <a href="#">Delete</a>
                <div class='clear'></div>
            </div>
        </div>

    <?php } ?>

</div>