
<style>
    .theme_name label {
        background: #000000;
        color: #FFFFFF;
        float: left;
        padding: 5px;
    }
    .theme_name{
        width: 100%;
        position: absolute;
        bottom:40px;
    }
    .theme_name label{
        padding:5px;
        float:left;
        
    }
    .themes-list .theme
    {
        position: relative;
    }

</style>
 

<div class="themes-list">
    <?php
    foreach ($this->app['themes'] as $theme)
    {
    ?>
        <div class="theme one-quarter float_1">
            <div class="theme_name trans">
                <label><?php echo $theme['theme_name'];?></label>   
            </div>
            <a href="<?php echo $this->app['url'];?>window/theme/themeid/<?php echo $theme['theme_id'];?>" class="editTheme">
                <img src="themes/<?php echo $theme['theme_folder']; ?>/screenshot.jpg" width="100%" height="170">
            </a>
            <div class="controll">
                <a href="<?php echo $this->app['url'];?>window/theme/themeid/<?php echo $theme['theme_id'];?>" title="<?php echo $this->translate('edit');?>" class='editTheme icon-25x25 edit'></a>
                
                <a href="?theme=<?php echo $theme['theme_id'];?>" class="disAjax icon-25x25 screen" title="<?php echo $this->translate('preview');?>"></a>
                
                <a href="<?php echo $this->app['url'];?>/window/deleteTheme/themeId/<?php echo $theme['theme_id'];?>" class="btn2 icon-25x25 delete"  data-modal-type="confirm" data-modal-msg="<?php echo $this->translate('do_you_want_to_delete_theme');?>" title="<?php echo $this->translate('delete');?>"></a>
                <div class='clear'></div>
            </div>
        </div>
    <?php } ?>
</div>