<div class="sidebarItem float_1">
    <p><button href="<?php echo $this->app['url'];?>window/category/do/add/themeid/<?php echo $this->app['theme']['theme_id'];?>" class="btn">Add New Child Template</button></p>
</div>

<div class="sidebarItem float_1">
    <p><button href="<?php echo $this->app['url'];?>window/category/do/add/themeid/<?php echo $this->app['theme']['theme_id'];?>" class="btn margin-left-5">Copy The Template to</button></p>
</div>

<div class="sidebarItem float_1">
    <p><button href="<?php echo $this->app['url'];?>window/category/do/add/themeid/<?php echo $this->app['theme']['theme_id'];?>" class="btn margin-left-5">Move The Template to</button></p>
</div>
<div class="sidebarItem float_1">
    <p><button href="<?php echo $this->app['url'];?>window/category/do/add/themeid/<?php echo $this->app['theme']['theme_id'];?>" class="btn margin-left-5">Delete Template</button></p>
</div>
