<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">

    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <base href="<?php echo $this->baseUrl(); ?>/">
    <?php $theme_url = $this->baseUrl() . "/themes/mycms/"; ?>
    <link href="<?php echo $theme_url;?>/reset.css" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->baseUrl(); ?>/contents/assets/grids/960g/960_12_col.css" rel="stylesheet" type="text/css">
    <link href="<?php echo $theme_url;?>/style.css" rel="stylesheet" type="text/css">
    <script src="<?php echo $content_url; ?>js/jquery.js"></script>
    <script src="<?php echo $content_url; ?>js/js.js"></script>
</head>

<body>
<div class="main-nav">
    <ul class="nav container_12">
        <li><a href="#"><?php echo $this->translate('documentation');?></a></li>
        <li><a href="#"><?php echo $this->translate('applications');?></a></li>
        <li><a href="#"><?php echo $this->translate('hooks');?></a></li>
        <li><a href="#"><?php echo $this->translate('plugins');?></a></li>
        <li><a href="#"><?php echo $this->translate('themes');?></a></li>
        <li><a href="#"><?php echo $this->translate('community');?></a></li>
        <li><a href="#"><?php echo $this->translate('blog');?></a></li>
    </ul>
    <div class="clear"></div>
</div>

<div class="container_12">
    <div class='main_content'>
        <?php echo $this->plugins->renderGrids(); ?>
    </div>
</div>

</body>
</html>