<table class="table">
    <thead>
        <tr>
        <th><?php echo $this->translate('application'); ?></th>
        <th><?php echo $this->translate('version'); ?></th>
        <th><?php echo $this->translate('status'); ?></th>
        <th><?php echo $this->translate('action'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->app['applicationsList'] as $app){ ?>
        <tr>
        <td><a href='<?php echo $app['url']; ?>' class="app_name"><?php echo $app['app_name']; ?></a></td>
        <td><?php echo $app['version']; ?></td>
        <td class="color_<?php echo $app['app_status_color'];?>"><?php echo $this->translate($app['app_status']); ?></td>
        <td><a href="<?php echo $app['action_url'];?>" class="disState"><img src="contents/applications/AppsManager/<?php echo $app['action'];?>.png" width="16" height="16"></a></td>
        </tr>    
    <?php } ?>    
    </tbody>
</table>