<div class="row-fluid">
    
    <div class="span10">
    <?php if (!$this->app['plugins']){?>
        <?php echo $this->appendMessage('There is no Plugins', 'error'); ?>
    <?php }else{?>
        <form method="post" action="<?php echo $this->app['url']; ?>window/deletePlugin/group_id/<?php echo $this->app['group_id']; ?>/do/delete">
            <div class="panel clearfix">
                <div class="content no-pad clearfix">   
                    <table class="table">
                        <thead>
                            <tr>
                            <th width="1" colspan="3"><input type="checkbox" class="check_all" rel="plugin"></th>
                            <th>Plugin Name</th>
                            <th>Status</th>
                            </tr>
                        </thead>

                        <tbody class="tableSortable" rel="<?php echo $this->app['url']; ?>window/savePluginOrder">
                            <?php foreach ($this->app['plugins'] as $c => $plugin){?>
                                <tr id="order_<?php echo $plugin['plugin_id']; ?>">
                                <td width="1"><div class='sort-handle'></div></td>
                                <td width="1"><?php echo $c + 1; ?></td>
                                <td width="1"><input type="checkbox" class="plugin" name="plugin_id[]" value="<?php echo $plugin['plugin_id']; ?>"></td>
                                <td><a href='<?php echo $this->app['url'] . 'window/plugin/do/edit/pluginid/' . $plugin['plugin_id']; ?>' class="group_name"><?php echo $plugin['plugin_name']; ?></a></td>
                                <td><?php echo $plugin['plugin_status']; ?></td>
                                </tr>    
                            <?php } ?>    
                        </tbody>

                    </table>
                </div>
            </div>
            <input type="submit" value="<?php echo $this->translate('delete'); ?>" class="btn"/>
        </form>
<?php } ?>
</div>
<div class="span2">
<?php echo $this->app['listPluginsResource'] ?>
</div>

</div>