<?php echo $this->doctype();?>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->translate('site_title');?></title>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <base href="<?php echo $this->baseUrl(); ?>/">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <link href="<?php echo $this->baseUrl(); ?>mycms/themes/default/reset.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl(); ?>mycms/Themes/default/style.css" rel="stylesheet" type="text/css">
        <?php $content_url = $this->baseUrl() . "mycms/themes/default/"; ?>
        <script src="<?php echo $content_url; ?>/js/jquery.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $content_url; ?>js/js.js"></script>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
    </head>
    <?php $translate = Zend_Registry::get('Zend_Translate');?>
    <body>
    <div class="wrapper nine-tenths">
        <div class="header">
            <div class="logo">
                <a href="#" title="<?php echo $translate->translate('site_title');?>"></a>
            </div>
            <div class="clear"></div>
        </div>

        <div class="clear"></div>
        <div class="content-wrapper">
            <?php echo $this->plugins->renderGrids(); ?>
        </div>
    </div>
    </body>
</html>