<?php
if (!$this->app['fields']){
    echo $this->appendMessage($this->translate('no_fields_for_this_folder'), 'error');
}else{
?>
<form method="post" action="<?php echo $this->app['url'];?>window/deleteField">
<div class="panel clearfix">
            <div class="content no-pad clearfix">
                <table class="table" width="100%">
                    <thead>
                        <tr>
                        <th width="1"><input type="checkbox" class="check_all" rel="fields"></th>
                        <th ><?php echo $this->translate('field_name'); ?></th>
                        
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->app['fields'] as $field)
                        {

                            ?>
                            <tr>
                            <td><input type="checkbox" class="fields" name="field_id[]" value="<?php echo $field['field_id']; ?>"></td>
                            <td><a href='<?php echo $this->app['url']; ?>window/field/field_id/<?php echo $field['field_id']; ?>/do/edit' class="name">
                                <?php echo ($field['field_label'] == "")?$field['field_name']:$field['field_label']; ?>
                                </a></td>
                            
                            </tr>    
    <?php } ?>    
                    </tbody>

                </table>
                <div class="margin-top-5px">
                    <input type="hidden" name="folder_id" value="<?php echo $this->app['folder']['folder_id'];?>" >
                    <input type="submit" data-modal-type="confirm"  data-modal-msg="<?php echo $this->translate('do_you_want_delete_field');?>" value="<?php echo $this->translate('deletes'); ?>" name="deleteCats" class="btn">
                </div>
            </div>
        </div>
</form>
    <?php } ?>    
