
<?php

if (!$this->app['fields'])
{
    echo $this->appendMessage($this->translate('There is no fields in this category'), 'error');
}
else
{
?>


<div class="panel clearfix">
            <div class="content no-pad clearfix">
                <table class="table" width="100%">
                    <thead>
                        <tr>
                        <th width="1"><input type="checkbox" class="check_all" rel="cats"></th>
                        <th ><?php echo $this->translate('field_name'); ?></th>
                        
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->app['fields'] as $field)
                        {

                            ?>
                            <tr>
                            <td><input type="checkbox" class="fields" name="field[]" value="<?php echo $field['field_id']; ?>"></td>
                            <td><a href='<?php echo $this->app['url']; ?>window/field/field_id/<?php echo $field['field_id']; ?>/do/edit' class="name">
                                <?php echo ($field['field_label'] == "")?$field['field_name']:$field['field_label']; ?>
                                </a></td>
                            
                            </tr>    
    <?php } ?>    
                    </tbody>

                </table>
                <div class="margin-top-5px">
                    <input type="submit" data-modal-type="confirm"  data-modal-msg="Do you want delete this field?" value="<?php echo $this->translate('delete'); ?>" name="deleteCats" class="btn btn-navbar delete">
                </div>
            </div>
        </div>
    <?php } ?>    
