<?php
if (sizeof($this->app['itemsList']) == 0) {
    echo $this->appendMessage($this->translate('There is no items for this category'), 'error');
} else {
    ?>
    <form method="post" action="<?php echo $this->app['url']; ?>window/deleteItem">
        <div class="panel clearfix">
            <div class="content no-pad clearfix">
                <table class="table" width="100%">
                    <thead>
                        <tr>
                            <th width="1">#</th>
                            <th width="1"><input type='checkbox' class="check_all" rel="item"></th>
                            <th><?php echo $this->translate('Post Title');?></th>
                            <th width="100"><?php echo $this->translate('Auther');?></th>
                            <th width="100"><?php echo $this->translate('Publish Date');?></th>
                            <th width="10"><?php echo $this->translate('Status');?></th>
                            <th width="10"><?php echo $this->translate('action');?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->app['itemsList'] as $item_k => $item) { ?>
                            <tr>
                                <td><?php echo++$item_k; ?></td>
                                <td><input type="checkbox" class="item" name="item[]" value="<?php echo $item['item_id']; ?>"></td>
                                <td><a href='<?php echo $this->app['url'] . 'window/item/do/edit'; ?>/itemid/<?php echo $item['item_id']; ?>' class="openItem"><?php echo $item['item_title']; ?></a></td>
                                <td><?php echo $item['auther']; ?> Solaiman Kmail</td>
                                <td><?php echo date('Y-m-d h:i', $item['publish_date']); ?></td>
                                <td><?php echo $item['item_status']; ?></td>
                                <td>
                                    <a href='<?php echo $this->app['url'] . 'window/deleteItem'; ?>/itemid/<?php echo $item['item_id']; ?>/catId/<?php echo $this->app['catInfo']['cat_id'];?>' class="disState icon-25x25 delete" title="<?php echo $this->translate('delete');?>" data-modal-type="confirm" data-modal-msg="<?php echo $this->translate('do_you_want_delete_item');?>">

                                    </a></td>
                            </tr>    
                        <?php } ?>    
                    </tbody>
                </table>

                <div class="margin-top-5px">
                    <input type="hidden" name="cat_id" value="<?php echo $this->app['catInfo']['cat_id'];?>">
                    <input type="submit" value="<?php echo $this->translate('delete');?>" name="deleteItems" class="btn btn-navbar" data-modal-type="confirm" data-modal-msg="<?php echo $this->translate('do_you_want_delete_items');?>">
                </div>
            </div>
        </div>
    </form>
<?php } ?>