<?php
if (count($this->app['usergroupsList']) == 0) {
    echo $this->appendMessage($this->translate('not_found_usergroups'), 'error');
} else {
    ?>
    <div class="panel clearfix">
        <div class="content no-pad clearfix">
            <table class="table" width="100%">
                <thead>
                    <tr>
                        <th width="1">#</th>
                        <th width="1"><input type='checkbox' class="check_all" rel="usergroup"></th>
                        <th><?php echo $this->translate('Usergroup name');?></th>
                        <th width="15%"><?php echo $this->translate('action');?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->app['usergroupsList'] as $ug_k => $usergroup) { ?>
                        <tr>
                            <td><?php echo++$ug_k; ?></td>
                            <td><input type="checkbox" class="usergroup"></td>
                            <td><a href='<?php echo $this->app['url'] . 'window/users'; ?>/usergroupId/<?php echo $usergroup['usergroup_id']; ?>'><?php echo $usergroup['usergroup_name']; ?></a></td>
                         
                            <td align="center">
                                <a href="<?php echo $this->app['url'];?>window/user/do/add/usergroupId/<?php echo $usergroup['usergroup_id'];?>" class="icon-25x25 add-user" title="<?php echo $this->translate('add_user');?>"></a>
                                
                                <a href="<?php echo $this->app['url'] . 'window/usergroup/do/edit'; ?>/ugid/<?php echo $usergroup['usergroup_id']; ?>"  class="icon-25x25 edit" title="<?php echo $this->translate('edit');?>"></a>

                                <a href="<?php echo $this->app['url'];?>window/permissions/ugid/<?php echo $usergroup['usergroup_id'];?>" title="<?php echo $this->translate('permissions');?>" class="icon-25x25 lock"></a>

                                <a href="<?php echo $this->app['url'];?>window/fields/ugid/<?php echo $usergroup['usergroup_id'];?>" title="<?php echo $this->translate('fields');?>" class="icon-25x25 fields">
                                </a>
                            </td>
                        </tr>    
                    <?php } ?>    
                </tbody>

            </table>
        </div>

    </div>
<?php } ?>