<?php
if (sizeof($this->app['pagesList']) == 0) {
    echo $this->appendMessage($this->translate('no_pages_found'), 'error');
} else {
    ?>
    <div class="panel clearfix">
        <div class="content no-pad clearfix">
            <table class="table" width="100%">
                <thead>
                    <tr>
                        <th width="1">#</th>
                        <th width="1"><input type='checkbox' class="check_all" rel="usergroup"></th>
                        <th><?php echo $this->translate('page name');?></th>
                        <th width="190"><?php echo $this->translate('page_status');?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->app['pagesList'] as $ug_k => $page) { ?>
                        <tr>
                            <td><?php echo++$ug_k; ?></td>
                            <td><input type="checkbox" class="usergroup"></td>
                            <td><a href='<?php echo $page['url'];?>'><?php echo $page['user_page_name']; ?></a></td>
                         
                            <td>

                            </td>
                        </tr>    
                    <?php } ?>    
                </tbody>

            </table>
        </div>

    </div>
<?php } ?>