<form method="post" action="<?php echo $this->app['url'];?>window/savePerm">
<style>
    .permsTable{
        display: none;
    }
    .permsTable label{
        font-size:12px;
        display: inline;
    }

    .permsTable label input[type=radio]{
        margin:0 5px;
    }

    .slideDown{
        cursor: pointer;
    }
    table .select_all,.perm{
        margin-top:8px;
    }
    .perm_label_0{
        color:red;
    }
    .perm_label_1{
        color:green;
    }.perm_label_2{
         color:orange;
     }
</style>

<script>
    $(function(){

        $('.slideDown').die().live('click',function(){

            rel = $(this).attr('rel');

            if(!$('.'+rel).is(':visible')){
                $('.slideDown').removeClass('active_heading_1');
                $(this).addClass('active_heading_1');
                $('.'+rel).slideDown('fast');
            }
            else{

                $('.'+rel).slideUp('fast');
                $(this).removeClass('active_heading_1');
            }
        });

        $('.fullControll').live('click',function(){
            $('.permsTable').slideDown();
        });

        $('.select_all').live('change',function(){
            $('.'+$(this).attr('rel') + '  option[value='+$(this).val()+']').attr('selected',true);
        });
    });
</script>


<div class="one-fifth float_1">
    <div class="box">
        <div class="box_head">
            <?php echo $this->translate('additional_permissions');?>
        </div>
        <div class="box_content">
            <label for="perm_super_admin">
                <input type="hidden" name="super_admin" value="0">
                <input type="checkbox" name="super_admin" value="1" id="perm_super_admin" <?php echo ($this->app['super_admin'] == 1 ?  'checked':'' );?>>
                <?php echo $this->translate('super_admin');?>
            </label>
        </div>
    </div>
</div>
<div class="four-fifths  float_2">
<?php foreach ($this->app['applications'] as $app) { ?>
    <div class="panel clearfix headings_panel">
        <div class="content no-pad clearfix">
            
            <div class="slideDown heading_1" rel="permsTable_<?php echo $app['app_prefix'].'_'.$app['app_id'];?>">
                <?php echo $this->translate($app['app_name']);;?>
            </div>
            
            <table class="table permsTable permsTable_<?php echo $app['app_prefix'].'_'.$app['app_id'];?>">
                <thead>
                <tr>
                    <th></th>
                    <?php foreach($this->app['default_permissions'][$app['app_prefix']] as $perm=>$methodsList){?>
                        <th>
                            <?php echo $perm;?>
                        </th>
                    <?php } ?>
                </tr>
                <tr>
                    <th></th>
                    <?php foreach($this->app['default_permissions'][$app['app_prefix']] as $perm=>$methodsList){?>
                        <th>
                            <select class="select_all perm input-mini" rel="perm_<?php echo $app['app_prefix'];?>_<?php echo $perm;?>"  name="perm[<?php echo $app['app_prefix'];?>][methods][<?php echo $method;?>][<?php echo $perm;?>]">
                                <?php foreach($this->app['permsLabels'] as $key=>$methodsList){?>
                                    <?php if($this->app['permissionFor'] != 'usergroup' || $key != 2 ){?>
                                        <option value="<?php echo $key;?>" class='<?php echo 'perm_label_'.$key;?>' <?php if($this->app['perms'][$app['app_prefix']]['methods'][$method][$perm] == $key){echo "selected='selected'";}?>>
                                            <?php echo $this->translate('perm_label_'.$key);?>
                                        </option>
                                    <?php } ?>

                                <?php } ?>
                            </select>

                        </th>
                    <?php } ?>
                </tr>

                </thead>
                <tbody>
                    <?php foreach($app['methods'] as $method){ ?>
                    <tr>
                        <td width="200" align="right">
                            <?php
                                if($method == '__construct'){
                                    echo 'Access';
                                }else
                                    echo $method;
                                $method = strtolower($method);
                             ?>
                        </td>
                        <?php foreach($this->app['default_permissions'][$app['app_prefix']] as $perm=>$methodsList){?>
                            <td>
                                <?php if(count($methodsList) == 0 || in_array($method, $methodsList)){?>
                                    <select
                                        name="perm[<?php echo $app['app_prefix'];?>][methods][<?php echo $method;?>][<?php echo $perm;?>]"
                                        class="input-mini perm perm_<?php echo $app['app_prefix'];?>_<?php echo $perm;?>">
                                    <?php foreach($this->app['permsLabels'] as $key=>$label){?>
                                        <?php if($this->app['permissionFor'] != 'usergroup'  || $key != 2 ){?>
                                        <option  value="<?php echo $key;?>" class="<?php echo 'perm_label_'.$key;?>"
                                            <?php if($this->app['perms'][$app['app_prefix']]['methods'][$method][$perm] == $key){echo "selected='selected'";}?>>
                                            <?php echo $this->translate('perm_label_'.$key);?>
                                        </option>
                                        <?php } ?>
                                    <?php } ?>
                                    </select>
                                <?php }?>
                            </td>                            
                        <?php } ?>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
            <?php if(isset($app['tables']))
                      foreach($app['tables'] as $tableName=>$table){
            ?>
            <table class="table permsTable permsTable_<?php echo $app['app_prefix'].'_'.$app['app_id'];?>">
                <thead>
                <tr>
                    <th><?php echo $tableName;?></th>
                    <?php foreach($this->app['default_permissions'][$app['app_prefix']] as $perm=>$methodsList){?>
                        <th>
                            <?php echo $perm;?>
                        </th>
                    <?php } ?>
                </tr>

                <tr>
                    <th><?php echo $tableName;?></th>
                    <?php foreach($this->app['default_permissions'][$app['app_prefix']] as $perm=>$methodsList){?>
                        <th>
                            <select name="perm_<?php echo $app['app_prefix'];?>_tables_<?php echo $perm;?>" class="input-mini select_all perm" rel="perm_<?php echo $app['app_prefix'];?>_tables_<?php echo $perm;?>">
                            <?php foreach($this->app['permsLabels'] as $key=>$methodsList){?>
                                <?php if($this->app['permissionFor'] != 'usergroup'  || $key != 2 ){?>
                                         <option value="<?php echo $key;?>" >
                                        <?php echo $this->translate('perm_label_'.$key);?>
                                    </option>
                                <?php } ?>
                            <?php } ?>
                            </select>
                        </th>
                    <?php } ?>
                </tr>


                </thead>
                <tbody>
                    <?php foreach($table['data'] as $data){?>
                    <tr>
                        <td width="200" align="right">
                            <?php echo $data[$table['label']] . $data[$table['key']];?>
                        </td>
                        <?php foreach($this->app['default_permissions'][$app['app_prefix']] as $perm=>$methodsList){?>
                        <td>
                            <?php if(count($methodsList) == 0 || in_array($method, $methodsList)){?>
                                <select  class="input-mini perm perm_<?php echo $app['app_prefix'];?>_tables_<?php echo $perm;?>" name="perm[<?php echo $app['app_prefix'];?>][tables][<?php echo $tableName;?>][<?php echo $data[$table['key']];?>][<?php echo $perm;?>]">
                                <?php foreach($this->app['permsLabels'] as $key=>$label){?>
                                    <?php if($this->app['permissionFor'] != 'user' && $key != 2 ){?>
                                        <option value="<?php echo $key;?>" <?php if($this->app['perms'][$app['app_prefix']]['tables'][$tableName][$data[$table['key']]][$perm] == 2){echo "selected='selected'";}?>   >
                                            <?php echo $this->translate('perm_label_'.$key);?>
                                        </option>
                                    <?php } ?>
                                <?php } ?>
                                </select>

                            <?php }?>
                        </td>
                        <?php } ?>
                             
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
            
            
            
            <?php }?>
            
        </div>
    </div>

<?php } ?>
</div>


    <div class="clear"></div>
    <?php if($this->app['permissionFor'] == 'user'){?>
    <input type="hidden" name="user_id" value="<?php echo $this->app['item'][0]['user_id'];?>">
    <?php } ?>
    <?php if($this->app['permissionFor'] == 'usergroup'){?>
    <input type="hidden" name="usergroup_id" value="<?php echo $this->app['item']['usergroup_id'];?>">
    <?php } ?>
        
    <input type="submit" class="btn" name="save" value="Save" >

</form>


