<!DOCTYPE html>
<html lang="en" dir="<?php echo $this->dir(); ?>">
    <head>
        <base href="<?php echo $this->assetsUrl(); ?>" target="_blank">
        <meta charset="UTF-8">
        <title>MyCMS - Solaiman Kmail</title>

        <?php $content_url = "contents/admin/themes/default/"; ?>

        <?php echo $this->AppendMessage('', '', true); ?>


        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

        <script src="<?php echo $content_url; ?>js/jquery.js"></script>
        <script src="<?php echo $content_url; ?>js/jqueryui/jquery-ui-1.9.2.core.js"></script>
        <script src="<?php echo $content_url; ?>js/jqueryui/jquery.ui.sortable.min.js"></script>
        <script src="<?php echo $content_url; ?>js/jqueryui/jquery.ui.droppable.js"></script>
        <script src="<?php echo $content_url; ?>js/jqueryui/jquery.ui.draggable.min.js"></script>

        <script src="<?php echo $content_url; ?>js/jqueryui/jqueryui.js"></script>

        <script src="<?php echo $content_url; ?>bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $content_url; ?>js/jquery.plugins/validation/jquery.validate.min.js"></script>
        <script src="<?php echo $content_url; ?>js/jqueryui/settings.js"></script>
        <script src="<?php echo $content_url; ?>js/jquery.form.js"></script>
        <script type="text/javascript" src="<?php echo $content_url; ?>_layout/scripts/bootbox.min.js"></script>

        <script src="<?php echo $content_url; ?>js/js_settings.js"></script>
        <script src="<?php echo $content_url; ?>js/jquery.pjax.js"></script>
        <script src="<?php echo $content_url; ?>js/ajaxOpenWindow.js"></script>
        <script src="<?php echo $content_url; ?>js/ajaxSubmitForm.js"></script>
        <script src="<?php echo $content_url; ?>js/jquery.plugins/uploader.js"></script>
        <script type="text/javascript" src="<?php echo $content_url; ?>js/editor/ckeditor.js"></script>
        <script type="text/javascript" src="<?php echo $content_url; ?>js/editor/adapters/jquery.js"></script>



         <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="<?php echo $content_url; ?>/_layout/core.css" type="text/css" />
        <link rel="stylesheet" href="<?php echo $content_url; ?>/_layout/style.css" type="text/css" />

    </head>
    <body class="<?php echo $this->dir(); ?>">

        <div id="top-navigation" class="span12" >
            <?php echo $this->layout()->render('head'); ?>
            <div class="clear"></div>
        </div>
        <?php  echo $this->layout()->app['nav'];?>
    <div id="wrapper">
            <div class="row-fluid hidden-desktop">
                <select class="span12" id="goToApplication">
                    <?php foreach($this->layout()->applications as $app){?>
                    <option value="<?php echo $app['url'].$app['app_prefix'];?>"
                        <?php echo ($this->layout()->app['app_prefix'] == $app['app_prefix'])?'selected':'';?>
                        >
                        <?php echo $app['app_name'];?>
                    </option>
                    <?php  } ?>
                </select>                
            </div>

                <div id="sidebar" class="span2 visible-desktop">
                    <?php echo $this->layout()->render('sidebar'); ?>
                </div>
                <div id="content-side" class=" main-content span10">
                    <?php echo $this->layout()->content; ?>

                </div>
                <div class="clear"></div>
        </div>
        <script type="text/javascript" src="<?php echo $content_url; ?>js/editor/config.js"></script>

    </body>
</html>