<div class="content-controlls clear" style="<?php if($this->app['sidebar'] == false){?>display:none;<?php } ?>">
    <?php echo $this->app['sidebar']; ?>
    <div class="clear"></div>
</div>       

<?php 
    if($this->app['message']['text'] != "" && $this->app['message']['type'] != "")
    {
        echo $this->appendMessage($this->app['message']['text'],$this->app['message']['type']);
    }
?>
<div class="body">
    <?php echo $this->app['body']; ?>
    <div class="clear"></div>
</div>
