

<?php if($this->app['sidebar'] != ""){?>
<div class="content-controlls clear" style="display:block;">
    <?php echo $this->app['sidebar']; ?>
    <div class="clear"></div>
</div>       
<?php } ?>
<?php 
    if($this->app['message']['text'] != "" && $this->app['message']['type'] != "")
    {
        echo $this->appendMessage($this->app['message']['text'],$this->app['message']['type']);
    }
?>
<div class="body">
    <?php echo $this->app['body']; ?>
    <div class="clear"></div>
</div>
